### ISSUE TITLE
 undefined symbol: MPI_UNWEIGHTED

### ISSUE THREAD

**Issue by adyotag** [uqfoundation/pyina#63]
I loaded the intel-mkl module and installed pyina using pip using https://edbennett.github.io/high-performance-python/08-pathos/index.html 

However, I'm getting an error upon importing ez_map - ImportError: /home/agupta87/.conda/envs/DEM_SPHERES/lib/python3.8/site-packages/mpi4py/MPI.cpython-38-x86_64-linux-gnu.so: undefined symbol: MPI_UNWEIGHTED

I've tried modifying the path by adding the path to the conda environment, but that didn't work either.

**Comment by mmckerns** [comment]
If you are getting an undefined symbol error, this is coming from the C++ shared object `MPI.cpython-38-x86_64-linux-gnu.so` missing a dependency (often due to an incorrect version of a library being linked in the path).  It looks like it's coming from the build/install of cythonized MPI code from `mpi4py`.   I don't think anything can be done from `pyina` to ensure the MPI library is built/linked to the `mpi4py` code... you may want to try the `mpi4py` developers -- or check which version of the libraries are in your path and being linked. I'm going to close this as void, but do feel free to follow up here.
